# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'chooseHeadShot.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(381, 312)
        self.but1 = QtWidgets.QPushButton(Form)
        self.but1.setGeometry(QtCore.QRect(30, 30, 81, 81))
        self.but1.setText("")
        self.but1.setObjectName("but1")
        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setGeometry(QtCore.QRect(140, 130, 101, 121))
        self.groupBox.setStyleSheet("font-size: 15px;\n"
"border: 2px solid rgb(111, 156, 207);\n"
"border-radius: 4px;\n"
"margin-top: 10px;")
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.but2 = QtWidgets.QPushButton(Form)
        self.but2.setGeometry(QtCore.QRect(150, 30, 81, 81))
        self.but2.setText("")
        self.but2.setObjectName("but2")
        self.but3 = QtWidgets.QPushButton(Form)
        self.but3.setGeometry(QtCore.QRect(270, 30, 81, 81))
        self.but3.setText("")
        self.but3.setObjectName("but3")
        self.but6 = QtWidgets.QPushButton(Form)
        self.but6.setGeometry(QtCore.QRect(270, 150, 81, 81))
        self.but6.setText("")
        self.but6.setObjectName("but6")
        self.but4 = QtWidgets.QPushButton(Form)
        self.but4.setGeometry(QtCore.QRect(30, 150, 81, 81))
        self.but4.setText("")
        self.but4.setObjectName("but4")
        self.but5 = QtWidgets.QPushButton(Form)
        self.but5.setGeometry(QtCore.QRect(150, 150, 81, 81))
        self.but5.setText("")
        self.but5.setObjectName("but5")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(150, 260, 81, 28))
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(Form)
        self.but1.clicked.connect(Form.choose)
        self.but2.clicked.connect(Form.choose)
        self.but3.clicked.connect(Form.choose)
        self.but4.clicked.connect(Form.choose)
        self.but5.clicked.connect(Form.choose)
        self.but6.clicked.connect(Form.choose)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.pushButton.setText(_translate("Form", "Confirm"))
