# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dialogue.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_WorkTimeChat(object):
    def setupUi(self, WorkTimeChat):
        WorkTimeChat.setObjectName("WorkTimeChat")
        WorkTimeChat.resize(970, 734)
        WorkTimeChat.setMaximumSize(QtCore.QSize(970, 750))
        self.chatList = QtWidgets.QTabWidget(WorkTimeChat)
        self.chatList.setGeometry(QtCore.QRect(0, 60, 292, 681))
        self.chatList.setObjectName("chatList")
        self.onlineUser = QtWidgets.QWidget()
        self.onlineUser.setObjectName("onlineUser")
        self.onlineList = QtWidgets.QListWidget(self.onlineUser)
        self.onlineList.setGeometry(QtCore.QRect(0, 0, 291, 651))
        self.onlineList.setStyleSheet("height:60px;")
        self.onlineList.setIconSize(QtCore.QSize(50, 50))
        self.onlineList.setObjectName("onlineList")
        item = QtWidgets.QListWidgetItem()
        self.onlineList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.onlineList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.onlineList.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.onlineList.addItem(item)
        self.chatList.addTab(self.onlineUser, "")
        self.searchResult = QtWidgets.QWidget()
        self.searchResult.setObjectName("searchResult")
        self.searchResList = QtWidgets.QListWidget(self.searchResult)
        self.searchResList.setGeometry(QtCore.QRect(0, 0, 292, 651))
        self.searchResList.setStyleSheet("height:60px;")
        self.searchResList.setIconSize(QtCore.QSize(50, 50))
        self.searchResList.setObjectName("searchResList")
        self.chatList.addTab(self.searchResult, "")
        self.inputText = QtWidgets.QPlainTextEdit(WorkTimeChat)
        self.inputText.setGeometry(QtCore.QRect(291, 541, 680, 151))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.inputText.setFont(font)
        self.inputText.setToolTip("")
        self.inputText.setStyleSheet("font: 10pt \"等线\";")
        self.inputText.setTabChangesFocus(True)
        self.inputText.setOverwriteMode(True)
        self.inputText.setBackgroundVisible(False)
        self.inputText.setObjectName("inputText")
        self.searchLine = QtWidgets.QLineEdit(WorkTimeChat)
        self.searchLine.setGeometry(QtCore.QRect(10, 15, 221, 30))
        font = QtGui.QFont()
        font.setFamily("等线")
        self.searchLine.setFont(font)
        self.searchLine.setObjectName("searchLine")
        self.searchButton = QtWidgets.QPushButton(WorkTimeChat)
        self.searchButton.setGeometry(QtCore.QRect(240, 10, 41, 41))
        self.searchButton.setText("")
        self.searchButton.setObjectName("searchButton")
        self.widget = QtWidgets.QWidget(WorkTimeChat)
        self.widget.setGeometry(QtCore.QRect(650, 380, 251, 131))
        self.widget.setStyleSheet("QWidget {\n"
"        background: rgba(255, 255, 255, 40%);\n"
"}")
        self.widget.setObjectName("widget")
        self.pushButton_3 = QtWidgets.QPushButton(self.widget)
        self.pushButton_3.setGeometry(QtCore.QRect(190, 10, 51, 51))
        self.pushButton_3.setText("")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.widget)
        self.pushButton_4.setGeometry(QtCore.QRect(130, 10, 51, 51))
        self.pushButton_4.setText("")
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.widget)
        self.pushButton_5.setGeometry(QtCore.QRect(70, 10, 51, 51))
        self.pushButton_5.setText("")
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(self.widget)
        self.pushButton_6.setGeometry(QtCore.QRect(10, 10, 51, 51))
        self.pushButton_6.setText("")
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_7 = QtWidgets.QPushButton(self.widget)
        self.pushButton_7.setGeometry(QtCore.QRect(10, 70, 51, 51))
        self.pushButton_7.setText("")
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_8 = QtWidgets.QPushButton(self.widget)
        self.pushButton_8.setGeometry(QtCore.QRect(70, 70, 51, 51))
        self.pushButton_8.setText("")
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_9 = QtWidgets.QPushButton(self.widget)
        self.pushButton_9.setGeometry(QtCore.QRect(130, 70, 51, 51))
        self.pushButton_9.setText("")
        self.pushButton_9.setObjectName("pushButton_9")
        self.pushButton_10 = QtWidgets.QPushButton(self.widget)
        self.pushButton_10.setGeometry(QtCore.QRect(190, 70, 51, 51))
        self.pushButton_10.setText("")
        self.pushButton_10.setObjectName("pushButton_10")
        self.name = QtWidgets.QLabel(WorkTimeChat)
        self.name.setGeometry(QtCore.QRect(310, 5, 321, 51))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(20)
        self.name.setFont(font)
        self.name.setObjectName("name")
        self.line = QtWidgets.QFrame(WorkTimeChat)
        self.line.setGeometry(QtCore.QRect(0, 58, 971, 2))
        self.line.setStyleSheet("color: rgb(120, 170, 220);")
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(WorkTimeChat)
        self.line_2.setGeometry(QtCore.QRect(290, 0, 2, 731))
        self.line_2.setStyleSheet("color: rgb(120, 170, 220);")
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.frame = QtWidgets.QFrame(WorkTimeChat)
        self.frame.setGeometry(QtCore.QRect(289, 499, 681, 42))
        self.frame.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.fileButton = QtWidgets.QPushButton(self.frame)
        self.fileButton.setGeometry(QtCore.QRect(625, 0, 41, 41))
        self.fileButton.setToolTipDuration(2)
        self.fileButton.setText("")
        self.fileButton.setObjectName("fileButton")
        self.picButton = QtWidgets.QPushButton(self.frame)
        self.picButton.setGeometry(QtCore.QRect(560, 0, 41, 41))
        self.picButton.setToolTipDuration(1)
        self.picButton.setText("")
        self.picButton.setObjectName("picButton")
        self.font_button = QtWidgets.QPushButton(self.frame)
        self.font_button.setGeometry(QtCore.QRect(20, 0, 41, 41))
        self.font_button.setToolTipDuration(2)
        self.font_button.setStyleSheet("font: 75 14pt \"等线\";\n"
"color: rgb(88, 88, 88);")
        self.font_button.setObjectName("font_button")
        self.clearMessage = QtWidgets.QPushButton(WorkTimeChat)
        self.clearMessage.setGeometry(QtCore.QRect(300, 700, 80, 25))
        self.clearMessage.setObjectName("clearMessage")
        self.sendMessage = QtWidgets.QPushButton(WorkTimeChat)
        self.sendMessage.setGeometry(QtCore.QRect(870, 700, 85, 25))
        self.sendMessage.setObjectName("sendMessage")
        self.widget_showText = QtWidgets.QWidget(WorkTimeChat)
        self.widget_showText.setGeometry(QtCore.QRect(282, 50, 695, 458))
        self.widget_showText.setMaximumSize(QtCore.QSize(701, 471))
        self.widget_showText.setObjectName("widget_showText")
        self.font_widget = QtWidgets.QWidget(WorkTimeChat)
        self.font_widget.setGeometry(QtCore.QRect(300, 400, 261, 101))
        self.font_widget.setStyleSheet("QWidget {\n"
"        background: rgba(255, 255, 255, 40%);\n"
"}\n"
"QSpinBox {\n"
"        border-radius: 4px;\n"
"        height: 24px;\n"
"        min-width: 40px;\n"
"        border: 0px solid rgb(111, 156, 207);\n"
"        background: white;\n"
"}\n"
"QSpinBox:enabled {\n"
"        color: rgb(60, 60, 60);\n"
"}\n"
"QSpinBox:enabled:hover, QSpinBox:enabled:focus {\n"
"        color: rgb(51, 51, 51);\n"
"}\n"
"QSpinBox::up-button {\n"
"        border-left: 1px solid rgb(111, 156, 207);\n"
"        width: 18px;\n"
"        height: 12px;\n"
"        border-top-right-radius: 4px;\n"
"        image: url(:/White/upButton);\n"
"}\n"
"QSpinBox::up-button:!enabled {\n"
"        background: transparent;\n"
"}\n"
"QSpinBox::up-button:enabled:hover {\n"
"        background: rgb(255, 255, 255, 30);\n"
"}\n"
"QSpinBox::down-button {\n"
"        border-left: 1px solid rgb(111, 156, 207);\n"
"        width: 18px;\n"
"        height: 12px;\n"
"        border-bottom-right-radius: 4px;\n"
"        image: url(:/White/downButton);\n"
"}\n"
"QSpinBox::down-button:!enabled {\n"
"        background: transparent;\n"
"}\n"
"QSpinBox::down-button:hover {\n"
"        background: rgb(255, 255, 255, 30);\n"
"}\n"
"QComboBox {\n"
"        height: 25px;\n"
"        border-radius: 4px;\n"
"        border: 0px solid rgb(111, 156, 207);\n"
"        background: white;\n"
"}\n"
"QComboBox:enabled {\n"
"        color: rgb(84, 84, 84);\n"
"}\n"
"QComboBox:enabled:hover, QComboBox:enabled:focus {\n"
"        color: rgb(51, 51, 51);\n"
"}\n"
"QComboBox::drop-down {\n"
"        width: 20px;\n"
"        border: none;\n"
"        background: transparent;\n"
"}\n"
"QComboBox::drop-down:hover {\n"
"        background: rgba(255, 255, 255, 30);\n"
"}\n"
"QComboBox::down-arrow {\n"
"        image: url(:/White/arrowBottom);\n"
"}\n"
"QComboBox::down-arrow:on {\n"
"        /**top: 1px;**/\n"
"}\n"
"QComboBox QAbstractItemView {\n"
"        border: 1px solid rgb(111, 156, 207);\n"
"        background: white;\n"
"        outline: none;\n"
"}\n"
"QComboBox QAbstractItemView::item {\n"
"        height: 25px;\n"
"        color: rgb(73, 73, 73);\n"
"}\n"
"QComboBox QAbstractItemView::item:selected {\n"
"        background: rgb(232, 241, 250);\n"
"        color: rgb(2, 65, 132);\n"
"}")
        self.font_widget.setObjectName("font_widget")
        self.formLayoutWidget = QtWidgets.QWidget(self.font_widget)
        self.formLayoutWidget.setGeometry(QtCore.QRect(0, 0, 261, 101))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.formLayout.setFieldGrowthPolicy(QtWidgets.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setLabelAlignment(QtCore.Qt.AlignCenter)
        self.formLayout.setFormAlignment(QtCore.Qt.AlignCenter)
        self.formLayout.setContentsMargins(8, 0, 7, 0)
        self.formLayout.setHorizontalSpacing(12)
        self.formLayout.setVerticalSpacing(19)
        self.formLayout.setObjectName("formLayout")
        self.la = QtWidgets.QLabel(self.formLayoutWidget)
        self.la.setObjectName("la")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.la)
        self.la2 = QtWidgets.QLabel(self.formLayoutWidget)
        self.la2.setObjectName("la2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.la2)
        self.font_box = QtWidgets.QComboBox(self.formLayoutWidget)
        self.font_box.setObjectName("font_box")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.font_box)
        self.font_size = QtWidgets.QComboBox(self.formLayoutWidget)
        self.font_size.setObjectName("font_size")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.font_size)
        self.widget_showText.raise_()
        self.chatList.raise_()
        self.clearMessage.raise_()
        self.sendMessage.raise_()
        self.inputText.raise_()
        self.searchLine.raise_()
        self.searchButton.raise_()
        self.widget.raise_()
        self.name.raise_()
        self.frame.raise_()
        self.line_2.raise_()
        self.line.raise_()
        self.font_widget.raise_()

        self.retranslateUi(WorkTimeChat)
        self.chatList.setCurrentIndex(0)
        self.fileButton.clicked.connect(WorkTimeChat.open_file_win)
        self.picButton.clicked.connect(WorkTimeChat.emoji_init)
        self.sendMessage.clicked.connect(WorkTimeChat.send_msg)
        self.clearMessage.clicked.connect(self.inputText.clear)
        self.searchButton.clicked.connect(WorkTimeChat.search)
        self.pushButton_10.clicked.connect(WorkTimeChat.push_but10)
        self.pushButton_9.clicked.connect(WorkTimeChat.push_but9)
        self.pushButton_8.clicked.connect(WorkTimeChat.push_but8)
        self.pushButton_7.clicked.connect(WorkTimeChat.push_but7)
        self.pushButton_6.clicked.connect(WorkTimeChat.push_but6)
        self.pushButton_5.clicked.connect(WorkTimeChat.push_but5)
        self.pushButton_4.clicked.connect(WorkTimeChat.push_but4)
        self.pushButton_3.clicked.connect(WorkTimeChat.push_but3)
        self.onlineList.itemClicked['QListWidgetItem*'].connect(WorkTimeChat.text_chat)
        self.onlineList.itemDoubleClicked['QListWidgetItem*'].connect(WorkTimeChat.show_info_clg)
        self.inputText.textChanged.connect(WorkTimeChat.sendPicture)
        self.font_button.clicked.connect(WorkTimeChat.font_change)
        self.searchResList.itemDoubleClicked['QListWidgetItem*'].connect(WorkTimeChat.srch_show_info)
        self.searchResList.itemClicked['QListWidgetItem*'].connect(WorkTimeChat.srch_text_chat)
        QtCore.QMetaObject.connectSlotsByName(WorkTimeChat)

    def retranslateUi(self, WorkTimeChat):
        _translate = QtCore.QCoreApplication.translate
        WorkTimeChat.setWindowTitle(_translate("WorkTimeChat", "Form"))
        __sortingEnabled = self.onlineList.isSortingEnabled()
        self.onlineList.setSortingEnabled(False)
        item = self.onlineList.item(0)
        item.setText(_translate("WorkTimeChat", "Amy"))
        item = self.onlineList.item(1)
        item.setText(_translate("WorkTimeChat", "Bill"))
        item = self.onlineList.item(2)
        item.setText(_translate("WorkTimeChat", "Cindy"))
        item = self.onlineList.item(3)
        item.setText(_translate("WorkTimeChat", "Juny"))
        self.onlineList.setSortingEnabled(__sortingEnabled)
        self.chatList.setTabText(self.chatList.indexOf(self.onlineUser), _translate("WorkTimeChat", "Online"))
        self.chatList.setTabText(self.chatList.indexOf(self.searchResult), _translate("WorkTimeChat", "Search"))
        self.name.setText(_translate("WorkTimeChat", "Chat"))
        self.fileButton.setToolTip(_translate("WorkTimeChat", "Upload and Download Files"))
        self.picButton.setToolTip(_translate("WorksearcTimeChat", "Sticker"))
        self.font_button.setToolTip(_translate("WorkTimeChat", "Upload and Download Files"))
        self.font_button.setText(_translate("WorkTimeChat", "A"))
        self.clearMessage.setText(_translate("WorkTimeChat", "Clear"))
        self.sendMessage.setText(_translate("WorkTimeChat", "Send"))
        self.la.setText(_translate("WorkTimeChat", "Font"))
        self.la2.setText(_translate("WorkTimeChat", "Font Size"))