# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'showGroupInformation.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_GrpInfo(object):
    def setupUi(self, GrpInfo):
        GrpInfo.setObjectName("GrpInfo")
        GrpInfo.resize(400, 300)
        self.groupBox = QtWidgets.QGroupBox(GrpInfo)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 381, 281))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.departmentName = QtWidgets.QLabel(self.groupBox)
        self.departmentName.setGeometry(QtCore.QRect(140, 80, 121, 16))
        self.departmentName.setObjectName("departmentName")
        self.groupName = QtWidgets.QLabel(self.groupBox)
        self.groupName.setGeometry(QtCore.QRect(10, 30, 291, 16))
        self.groupName.setObjectName("groupName")
        self.lable1 = QtWidgets.QLabel(self.groupBox)
        self.lable1.setGeometry(QtCore.QRect(10, 80, 121, 16))
        self.lable1.setObjectName("lable1")
        self.lable2 = QtWidgets.QLabel(self.groupBox)
        self.lable2.setGeometry(QtCore.QRect(10, 110, 171, 16))
        self.lable2.setObjectName("lable2")
        self.groupMembers = QtWidgets.QLabel(self.groupBox)
        self.groupMembers.setGeometry(QtCore.QRect(10, 140, 171, 16))
        self.groupMembers.setObjectName("groupMembers")
        self.line = QtWidgets.QFrame(self.groupBox)
        self.line.setGeometry(QtCore.QRect(10, 60, 151, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")

        self.retranslateUi(GrpInfo)
        QtCore.QMetaObject.connectSlotsByName(GrpInfo)

    def retranslateUi(self, GrpInfo):
        _translate = QtCore.QCoreApplication.translate
        GrpInfo.setWindowTitle(_translate("GrpInfo", "Dialog"))
        self.departmentName.setText(_translate("GrpInfo", "xx Department"))
        self.groupName.setText(_translate("GrpInfo", "GroupName"))
        self.lable1.setText(_translate("GrpInfo", "Group belons to"))
        self.lable2.setText(_translate("GrpInfo", "Group including: "))
        self.groupMembers.setText(_translate("GrpInfo", "Group members names"))
